# Generated by Django 5.2.5 on 2025-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_name_country_company_resume_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
